### ISSUE TITLE
Tests failing on Travis

### ISSUE THREAD

**Issue by lkapelevich** [lkapelevich/SDDiP.jl#13]
Air conditioning, vehicle location, and generation expansion examples hit numeric issues with GLPK 4.61.  I don't see the same issues with GLPK 4.52.

**Comment by odow** [comment]
Numerical issues in sddip.jl or sddp.jl?

**Comment by lkapelevich** [comment]
SDDiP. In the lagrangian solver.

**Comment by lkapelevich** [comment]
Became a lot more stable since #16
