### ISSUE TITLE
solutions

### ISSUE THREAD

**Issue by carlosverbran** [lkapelevich/SDDiP.jl#19]
Is there any way to retrive the solution results by var-stage-node?
Br,
CV

**Comment by odow** [comment]
Hi @carlosverbran,

You might need to elaborate on you mean by "solution results" a bit more so we can help.

SDDiP is built upon SDDP.jl (https://github.com/odow/SDDP.jl).

If you haven't read them, the docs contain a number of examples that detail how to do different things.
At the bottom of [Tutorial One: first steps](https://odow.github.io/SDDP.jl/latest/tutorial/01_first_steps.html), we show how to simulate a policy and record the results of variables in the model.

Cheers,
Oscar

**Comment by carlosverbran** [comment]
Thank you Oscar. That's exactly what I was looking for.
Br,
CV

**Comment by lkapelevich** [comment]
I've linked the SDDP documentation in the readme now.
