### ISSUE TITLE
f_approx not defined

### ISSUE THREAD

**Issue by EyobZewdie** [lkapelevich/SDDiP.jl#4]
When you run the level method and it hits the maximum number of iterations it fails with f_approx not defined.

**Comment by lkapelevich** [comment]
Hmm. If you terminate because you hit the maximum number of iterations, it means you haven't really provably converged.

**Comment by lkapelevich** [comment]
Does f_approx come out as NaN? Could you please send me some more details about the problem?

**Comment by EyobZewdie** [comment]
<img width="1435" alt="error_message" src="https://user-images.githubusercontent.com/16024845/30410276-3037e284-995e-11e7-849b-56f3cfafeed0.png">

**Comment by odow** [comment]
Is the dual feasible if the method terminates after max iterations?

**Comment by lkapelevich** [comment]
The issue is fixed by https://github.com/lkapelevich/SDDiP.jl/commit/162237e7ae5aa4fe932245a68cba6fabb55f7e24.
~~The dual is feasible, so we could be smarter and deliberately terminate early.~~
The dual is not necessarily feasible...
